server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/professor
    username: root
    password: admin12345
  output:
    ansi:
      enabled: ALWAYS

kafka:
  bootstrapAddress: localhost:9092
  publishTimeout: 1000
  eventTopicName: professor-events
  transactionalId: professor-id
