server:
  port: 8083

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/avalia
    username: root
    password: admin12345
  output:
    ansi:
      enabled: ALWAYS

kafka:
  bootstrapAddress: localhost:9092
  publishTimeout: 1000
  transactionalId: avalia-id
  eventTopicName: avalia-events
  consumerGroupId: avalia-service
  listenEventTopics: academic-events